name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if index.html exists
      run: ls -la site/index.html

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          set -e
          cd /var/www/simple-page
          docker stop simple-page || true
          docker rm simple-page || true
          export DOCKER_BUILDKIT=1
          docker build -t simple-page .
          docker run -d -p 8081:8081 --name simple-page simple-page
